package org.whatever.stockspider.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CompanyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    protected int offset;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    protected int limit;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    protected String sumCol;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    protected String groupSelClause;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public CompanyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public void setOffset(int offset) {
         this.offset = offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public int getOffset() {
          return offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public void setLimit(int limit) {
         this.limit = limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public int getLimit() {
          return limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    public String getSumCol() {
          return sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    public String getGroupSelClause() {
          return groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table company_info
    */
    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNull() {
            addCriterion("ORG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNotNull() {
            addCriterion("ORG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEqualTo(String value) {
            addCriterion("ORG_NAME =", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotEqualTo(String value) {
            addCriterion("ORG_NAME <>", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThan(String value) {
            addCriterion("ORG_NAME >", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NAME >=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThan(String value) {
            addCriterion("ORG_NAME <", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThanOrEqualTo(String value) {
            addCriterion("ORG_NAME <=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLike(String value) {
            addCriterion("ORG_NAME like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotLike(String value) {
            addCriterion("ORG_NAME not like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameIn(List<String> values) {
            addCriterion("ORG_NAME in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotIn(List<String> values) {
            addCriterion("ORG_NAME not in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameBetween(String value1, String value2) {
            addCriterion("ORG_NAME between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotBetween(String value1, String value2) {
            addCriterion("ORG_NAME not between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnIsNull() {
            addCriterion("ORG_NAME_EN is null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnIsNotNull() {
            addCriterion("ORG_NAME_EN is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnEqualTo(String value) {
            addCriterion("ORG_NAME_EN =", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnNotEqualTo(String value) {
            addCriterion("ORG_NAME_EN <>", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnGreaterThan(String value) {
            addCriterion("ORG_NAME_EN >", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NAME_EN >=", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnLessThan(String value) {
            addCriterion("ORG_NAME_EN <", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnLessThanOrEqualTo(String value) {
            addCriterion("ORG_NAME_EN <=", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnLike(String value) {
            addCriterion("ORG_NAME_EN like", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnNotLike(String value) {
            addCriterion("ORG_NAME_EN not like", value, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnIn(List<String> values) {
            addCriterion("ORG_NAME_EN in", values, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnNotIn(List<String> values) {
            addCriterion("ORG_NAME_EN not in", values, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnBetween(String value1, String value2) {
            addCriterion("ORG_NAME_EN between", value1, value2, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnNotBetween(String value1, String value2) {
            addCriterion("ORG_NAME_EN not between", value1, value2, "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNull() {
            addCriterion("INDUSTRY is null");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNotNull() {
            addCriterion("INDUSTRY is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryEqualTo(String value) {
            addCriterion("INDUSTRY =", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotEqualTo(String value) {
            addCriterion("INDUSTRY <>", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThan(String value) {
            addCriterion("INDUSTRY >", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThanOrEqualTo(String value) {
            addCriterion("INDUSTRY >=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThan(String value) {
            addCriterion("INDUSTRY <", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThanOrEqualTo(String value) {
            addCriterion("INDUSTRY <=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLike(String value) {
            addCriterion("INDUSTRY like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotLike(String value) {
            addCriterion("INDUSTRY not like", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryIn(List<String> values) {
            addCriterion("INDUSTRY in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotIn(List<String> values) {
            addCriterion("INDUSTRY not in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryBetween(String value1, String value2) {
            addCriterion("INDUSTRY between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotBetween(String value1, String value2) {
            addCriterion("INDUSTRY not between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andOrgTelIsNull() {
            addCriterion("ORG_TEL is null");
            return (Criteria) this;
        }

        public Criteria andOrgTelIsNotNull() {
            addCriterion("ORG_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andOrgTelEqualTo(String value) {
            addCriterion("ORG_TEL =", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelNotEqualTo(String value) {
            addCriterion("ORG_TEL <>", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelGreaterThan(String value) {
            addCriterion("ORG_TEL >", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_TEL >=", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelLessThan(String value) {
            addCriterion("ORG_TEL <", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelLessThanOrEqualTo(String value) {
            addCriterion("ORG_TEL <=", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelLike(String value) {
            addCriterion("ORG_TEL like", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelNotLike(String value) {
            addCriterion("ORG_TEL not like", value, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelIn(List<String> values) {
            addCriterion("ORG_TEL in", values, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelNotIn(List<String> values) {
            addCriterion("ORG_TEL not in", values, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelBetween(String value1, String value2) {
            addCriterion("ORG_TEL between", value1, value2, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgTelNotBetween(String value1, String value2) {
            addCriterion("ORG_TEL not between", value1, value2, "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgWebIsNull() {
            addCriterion("ORG_WEB is null");
            return (Criteria) this;
        }

        public Criteria andOrgWebIsNotNull() {
            addCriterion("ORG_WEB is not null");
            return (Criteria) this;
        }

        public Criteria andOrgWebEqualTo(String value) {
            addCriterion("ORG_WEB =", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebNotEqualTo(String value) {
            addCriterion("ORG_WEB <>", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebGreaterThan(String value) {
            addCriterion("ORG_WEB >", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_WEB >=", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebLessThan(String value) {
            addCriterion("ORG_WEB <", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebLessThanOrEqualTo(String value) {
            addCriterion("ORG_WEB <=", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebLike(String value) {
            addCriterion("ORG_WEB like", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebNotLike(String value) {
            addCriterion("ORG_WEB not like", value, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebIn(List<String> values) {
            addCriterion("ORG_WEB in", values, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebNotIn(List<String> values) {
            addCriterion("ORG_WEB not in", values, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebBetween(String value1, String value2) {
            addCriterion("ORG_WEB between", value1, value2, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andOrgWebNotBetween(String value1, String value2) {
            addCriterion("ORG_WEB not between", value1, value2, "orgWeb");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("PROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("PROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("PROVINCE =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("PROVINCE <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("PROVINCE >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("PROVINCE <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("PROVINCE like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("PROVINCE not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("PROVINCE in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("PROVINCE not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("PROVINCE between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("PROVINCE not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andRegAddressIsNull() {
            addCriterion("REG_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andRegAddressIsNotNull() {
            addCriterion("REG_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andRegAddressEqualTo(String value) {
            addCriterion("REG_ADDRESS =", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressNotEqualTo(String value) {
            addCriterion("REG_ADDRESS <>", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressGreaterThan(String value) {
            addCriterion("REG_ADDRESS >", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressGreaterThanOrEqualTo(String value) {
            addCriterion("REG_ADDRESS >=", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressLessThan(String value) {
            addCriterion("REG_ADDRESS <", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressLessThanOrEqualTo(String value) {
            addCriterion("REG_ADDRESS <=", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressLike(String value) {
            addCriterion("REG_ADDRESS like", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressNotLike(String value) {
            addCriterion("REG_ADDRESS not like", value, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressIn(List<String> values) {
            addCriterion("REG_ADDRESS in", values, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressNotIn(List<String> values) {
            addCriterion("REG_ADDRESS not in", values, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressBetween(String value1, String value2) {
            addCriterion("REG_ADDRESS between", value1, value2, "regAddress");
            return (Criteria) this;
        }

        public Criteria andRegAddressNotBetween(String value1, String value2) {
            addCriterion("REG_ADDRESS not between", value1, value2, "regAddress");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIsNull() {
            addCriterion("ADDRESS_POSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIsNotNull() {
            addCriterion("ADDRESS_POSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE =", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE <>", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeGreaterThan(String value) {
            addCriterion("ADDRESS_POSTCODE >", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE >=", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLessThan(String value) {
            addCriterion("ADDRESS_POSTCODE <", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE <=", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLike(String value) {
            addCriterion("ADDRESS_POSTCODE like", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotLike(String value) {
            addCriterion("ADDRESS_POSTCODE not like", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIn(List<String> values) {
            addCriterion("ADDRESS_POSTCODE in", values, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotIn(List<String> values) {
            addCriterion("ADDRESS_POSTCODE not in", values, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeBetween(String value1, String value2) {
            addCriterion("ADDRESS_POSTCODE between", value1, value2, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotBetween(String value1, String value2) {
            addCriterion("ADDRESS_POSTCODE not between", value1, value2, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeIsNull() {
            addCriterion("BUSINESS_SCOPE is null");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeIsNotNull() {
            addCriterion("BUSINESS_SCOPE is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeEqualTo(String value) {
            addCriterion("BUSINESS_SCOPE =", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeNotEqualTo(String value) {
            addCriterion("BUSINESS_SCOPE <>", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeGreaterThan(String value) {
            addCriterion("BUSINESS_SCOPE >", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_SCOPE >=", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeLessThan(String value) {
            addCriterion("BUSINESS_SCOPE <", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_SCOPE <=", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeLike(String value) {
            addCriterion("BUSINESS_SCOPE like", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeNotLike(String value) {
            addCriterion("BUSINESS_SCOPE not like", value, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeIn(List<String> values) {
            addCriterion("BUSINESS_SCOPE in", values, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeNotIn(List<String> values) {
            addCriterion("BUSINESS_SCOPE not in", values, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeBetween(String value1, String value2) {
            addCriterion("BUSINESS_SCOPE between", value1, value2, "businessScope");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_SCOPE not between", value1, value2, "businessScope");
            return (Criteria) this;
        }

        public Criteria andChairmanIsNull() {
            addCriterion("CHAIRMAN is null");
            return (Criteria) this;
        }

        public Criteria andChairmanIsNotNull() {
            addCriterion("CHAIRMAN is not null");
            return (Criteria) this;
        }

        public Criteria andChairmanEqualTo(String value) {
            addCriterion("CHAIRMAN =", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanNotEqualTo(String value) {
            addCriterion("CHAIRMAN <>", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanGreaterThan(String value) {
            addCriterion("CHAIRMAN >", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanGreaterThanOrEqualTo(String value) {
            addCriterion("CHAIRMAN >=", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanLessThan(String value) {
            addCriterion("CHAIRMAN <", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanLessThanOrEqualTo(String value) {
            addCriterion("CHAIRMAN <=", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanLike(String value) {
            addCriterion("CHAIRMAN like", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanNotLike(String value) {
            addCriterion("CHAIRMAN not like", value, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanIn(List<String> values) {
            addCriterion("CHAIRMAN in", values, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanNotIn(List<String> values) {
            addCriterion("CHAIRMAN not in", values, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanBetween(String value1, String value2) {
            addCriterion("CHAIRMAN between", value1, value2, "chairman");
            return (Criteria) this;
        }

        public Criteria andChairmanNotBetween(String value1, String value2) {
            addCriterion("CHAIRMAN not between", value1, value2, "chairman");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsIsNull() {
            addCriterion("INDEDIRECTORS is null");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsIsNotNull() {
            addCriterion("INDEDIRECTORS is not null");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsEqualTo(String value) {
            addCriterion("INDEDIRECTORS =", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsNotEqualTo(String value) {
            addCriterion("INDEDIRECTORS <>", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsGreaterThan(String value) {
            addCriterion("INDEDIRECTORS >", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsGreaterThanOrEqualTo(String value) {
            addCriterion("INDEDIRECTORS >=", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsLessThan(String value) {
            addCriterion("INDEDIRECTORS <", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsLessThanOrEqualTo(String value) {
            addCriterion("INDEDIRECTORS <=", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsLike(String value) {
            addCriterion("INDEDIRECTORS like", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsNotLike(String value) {
            addCriterion("INDEDIRECTORS not like", value, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsIn(List<String> values) {
            addCriterion("INDEDIRECTORS in", values, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsNotIn(List<String> values) {
            addCriterion("INDEDIRECTORS not in", values, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsBetween(String value1, String value2) {
            addCriterion("INDEDIRECTORS between", value1, value2, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsNotBetween(String value1, String value2) {
            addCriterion("INDEDIRECTORS not between", value1, value2, "indedirectors");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNull() {
            addCriterion("LEGAL_PERSON is null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNotNull() {
            addCriterion("LEGAL_PERSON is not null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonEqualTo(String value) {
            addCriterion("LEGAL_PERSON =", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotEqualTo(String value) {
            addCriterion("LEGAL_PERSON <>", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThan(String value) {
            addCriterion("LEGAL_PERSON >", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThanOrEqualTo(String value) {
            addCriterion("LEGAL_PERSON >=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThan(String value) {
            addCriterion("LEGAL_PERSON <", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThanOrEqualTo(String value) {
            addCriterion("LEGAL_PERSON <=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLike(String value) {
            addCriterion("LEGAL_PERSON like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotLike(String value) {
            addCriterion("LEGAL_PERSON not like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIn(List<String> values) {
            addCriterion("LEGAL_PERSON in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotIn(List<String> values) {
            addCriterion("LEGAL_PERSON not in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonBetween(String value1, String value2) {
            addCriterion("LEGAL_PERSON between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotBetween(String value1, String value2) {
            addCriterion("LEGAL_PERSON not between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andRegNumIsNull() {
            addCriterion("REG_NUM is null");
            return (Criteria) this;
        }

        public Criteria andRegNumIsNotNull() {
            addCriterion("REG_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andRegNumEqualTo(String value) {
            addCriterion("REG_NUM =", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumNotEqualTo(String value) {
            addCriterion("REG_NUM <>", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumGreaterThan(String value) {
            addCriterion("REG_NUM >", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumGreaterThanOrEqualTo(String value) {
            addCriterion("REG_NUM >=", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumLessThan(String value) {
            addCriterion("REG_NUM <", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumLessThanOrEqualTo(String value) {
            addCriterion("REG_NUM <=", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumLike(String value) {
            addCriterion("REG_NUM like", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumNotLike(String value) {
            addCriterion("REG_NUM not like", value, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumIn(List<String> values) {
            addCriterion("REG_NUM in", values, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumNotIn(List<String> values) {
            addCriterion("REG_NUM not in", values, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumBetween(String value1, String value2) {
            addCriterion("REG_NUM between", value1, value2, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegNumNotBetween(String value1, String value2) {
            addCriterion("REG_NUM not between", value1, value2, "regNum");
            return (Criteria) this;
        }

        public Criteria andRegCapitalIsNull() {
            addCriterion("REG_CAPITAL is null");
            return (Criteria) this;
        }

        public Criteria andRegCapitalIsNotNull() {
            addCriterion("REG_CAPITAL is not null");
            return (Criteria) this;
        }

        public Criteria andRegCapitalEqualTo(Integer value) {
            addCriterion("REG_CAPITAL =", value, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalNotEqualTo(Integer value) {
            addCriterion("REG_CAPITAL <>", value, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalGreaterThan(Integer value) {
            addCriterion("REG_CAPITAL >", value, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalGreaterThanOrEqualTo(Integer value) {
            addCriterion("REG_CAPITAL >=", value, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalLessThan(Integer value) {
            addCriterion("REG_CAPITAL <", value, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalLessThanOrEqualTo(Integer value) {
            addCriterion("REG_CAPITAL <=", value, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalIn(List<Integer> values) {
            addCriterion("REG_CAPITAL in", values, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalNotIn(List<Integer> values) {
            addCriterion("REG_CAPITAL not in", values, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalBetween(Integer value1, Integer value2) {
            addCriterion("REG_CAPITAL between", value1, value2, "regCapital");
            return (Criteria) this;
        }

        public Criteria andRegCapitalNotBetween(Integer value1, Integer value2) {
            addCriterion("REG_CAPITAL not between", value1, value2, "regCapital");
            return (Criteria) this;
        }

        public Criteria andSecucodeIsNull() {
            addCriterion("SECUCODE is null");
            return (Criteria) this;
        }

        public Criteria andSecucodeIsNotNull() {
            addCriterion("SECUCODE is not null");
            return (Criteria) this;
        }

        public Criteria andSecucodeEqualTo(String value) {
            addCriterion("SECUCODE =", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeNotEqualTo(String value) {
            addCriterion("SECUCODE <>", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeGreaterThan(String value) {
            addCriterion("SECUCODE >", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeGreaterThanOrEqualTo(String value) {
            addCriterion("SECUCODE >=", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeLessThan(String value) {
            addCriterion("SECUCODE <", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeLessThanOrEqualTo(String value) {
            addCriterion("SECUCODE <=", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeLike(String value) {
            addCriterion("SECUCODE like", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeNotLike(String value) {
            addCriterion("SECUCODE not like", value, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeIn(List<String> values) {
            addCriterion("SECUCODE in", values, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeNotIn(List<String> values) {
            addCriterion("SECUCODE not in", values, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeBetween(String value1, String value2) {
            addCriterion("SECUCODE between", value1, value2, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecucodeNotBetween(String value1, String value2) {
            addCriterion("SECUCODE not between", value1, value2, "secucode");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeIsNull() {
            addCriterion("SECURITY_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeIsNotNull() {
            addCriterion("SECURITY_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeEqualTo(String value) {
            addCriterion("SECURITY_TYPE =", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeNotEqualTo(String value) {
            addCriterion("SECURITY_TYPE <>", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeGreaterThan(String value) {
            addCriterion("SECURITY_TYPE >", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SECURITY_TYPE >=", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeLessThan(String value) {
            addCriterion("SECURITY_TYPE <", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeLessThanOrEqualTo(String value) {
            addCriterion("SECURITY_TYPE <=", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeLike(String value) {
            addCriterion("SECURITY_TYPE like", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeNotLike(String value) {
            addCriterion("SECURITY_TYPE not like", value, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeIn(List<String> values) {
            addCriterion("SECURITY_TYPE in", values, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeNotIn(List<String> values) {
            addCriterion("SECURITY_TYPE not in", values, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeBetween(String value1, String value2) {
            addCriterion("SECURITY_TYPE between", value1, value2, "securityType");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeNotBetween(String value1, String value2) {
            addCriterion("SECURITY_TYPE not between", value1, value2, "securityType");
            return (Criteria) this;
        }

        public Criteria andMarketIsNull() {
            addCriterion("MARKET is null");
            return (Criteria) this;
        }

        public Criteria andMarketIsNotNull() {
            addCriterion("MARKET is not null");
            return (Criteria) this;
        }

        public Criteria andMarketEqualTo(Integer value) {
            addCriterion("MARKET =", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotEqualTo(Integer value) {
            addCriterion("MARKET <>", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThan(Integer value) {
            addCriterion("MARKET >", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketGreaterThanOrEqualTo(Integer value) {
            addCriterion("MARKET >=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThan(Integer value) {
            addCriterion("MARKET <", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketLessThanOrEqualTo(Integer value) {
            addCriterion("MARKET <=", value, "market");
            return (Criteria) this;
        }

        public Criteria andMarketIn(List<Integer> values) {
            addCriterion("MARKET in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotIn(List<Integer> values) {
            addCriterion("MARKET not in", values, "market");
            return (Criteria) this;
        }

        public Criteria andMarketBetween(Integer value1, Integer value2) {
            addCriterion("MARKET between", value1, value2, "market");
            return (Criteria) this;
        }

        public Criteria andMarketNotBetween(Integer value1, Integer value2) {
            addCriterion("MARKET not between", value1, value2, "market");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIsNull() {
            addCriterion("OPEN_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIsNotNull() {
            addCriterion("OPEN_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andOpenStatusEqualTo(Integer value) {
            addCriterion("OPEN_STATUS =", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotEqualTo(Integer value) {
            addCriterion("OPEN_STATUS <>", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusGreaterThan(Integer value) {
            addCriterion("OPEN_STATUS >", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPEN_STATUS >=", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusLessThan(Integer value) {
            addCriterion("OPEN_STATUS <", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusLessThanOrEqualTo(Integer value) {
            addCriterion("OPEN_STATUS <=", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIn(List<Integer> values) {
            addCriterion("OPEN_STATUS in", values, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotIn(List<Integer> values) {
            addCriterion("OPEN_STATUS not in", values, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusBetween(Integer value1, Integer value2) {
            addCriterion("OPEN_STATUS between", value1, value2, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("OPEN_STATUS not between", value1, value2, "openStatus");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andListingDateIsNull() {
            addCriterion("LISTING_DATE is null");
            return (Criteria) this;
        }

        public Criteria andListingDateIsNotNull() {
            addCriterion("LISTING_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andListingDateEqualTo(Date value) {
            addCriterionForJDBCDate("LISTING_DATE =", value, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("LISTING_DATE <>", value, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateGreaterThan(Date value) {
            addCriterionForJDBCDate("LISTING_DATE >", value, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LISTING_DATE >=", value, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateLessThan(Date value) {
            addCriterionForJDBCDate("LISTING_DATE <", value, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LISTING_DATE <=", value, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateIn(List<Date> values) {
            addCriterionForJDBCDate("LISTING_DATE in", values, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("LISTING_DATE not in", values, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LISTING_DATE between", value1, value2, "listingDate");
            return (Criteria) this;
        }

        public Criteria andListingDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LISTING_DATE not between", value1, value2, "listingDate");
            return (Criteria) this;
        }

        public Criteria andNationIsNull() {
            addCriterion("NATION is null");
            return (Criteria) this;
        }

        public Criteria andNationIsNotNull() {
            addCriterion("NATION is not null");
            return (Criteria) this;
        }

        public Criteria andNationEqualTo(String value) {
            addCriterion("NATION =", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotEqualTo(String value) {
            addCriterion("NATION <>", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThan(String value) {
            addCriterion("NATION >", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationGreaterThanOrEqualTo(String value) {
            addCriterion("NATION >=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThan(String value) {
            addCriterion("NATION <", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLessThanOrEqualTo(String value) {
            addCriterion("NATION <=", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationLike(String value) {
            addCriterion("NATION like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotLike(String value) {
            addCriterion("NATION not like", value, "nation");
            return (Criteria) this;
        }

        public Criteria andNationIn(List<String> values) {
            addCriterion("NATION in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotIn(List<String> values) {
            addCriterion("NATION not in", values, "nation");
            return (Criteria) this;
        }

        public Criteria andNationBetween(String value1, String value2) {
            addCriterion("NATION between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andNationNotBetween(String value1, String value2) {
            addCriterion("NATION not between", value1, value2, "nation");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("GMT_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("GMT_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("GMT_MODIFIED =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("GMT_MODIFIED >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("GMT_MODIFIED <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("GMT_MODIFIED in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("GMT_MODIFIED not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(CODE) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(NAME) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andOrgNameLikeInsensitive(String value) {
            addCriterion("upper(ORG_NAME) like", value.toUpperCase(), "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameEnLikeInsensitive(String value) {
            addCriterion("upper(ORG_NAME_EN) like", value.toUpperCase(), "orgNameEn");
            return (Criteria) this;
        }

        public Criteria andIndustryLikeInsensitive(String value) {
            addCriterion("upper(INDUSTRY) like", value.toUpperCase(), "industry");
            return (Criteria) this;
        }

        public Criteria andOrgTelLikeInsensitive(String value) {
            addCriterion("upper(ORG_TEL) like", value.toUpperCase(), "orgTel");
            return (Criteria) this;
        }

        public Criteria andOrgWebLikeInsensitive(String value) {
            addCriterion("upper(ORG_WEB) like", value.toUpperCase(), "orgWeb");
            return (Criteria) this;
        }

        public Criteria andProvinceLikeInsensitive(String value) {
            addCriterion("upper(PROVINCE) like", value.toUpperCase(), "province");
            return (Criteria) this;
        }

        public Criteria andRegAddressLikeInsensitive(String value) {
            addCriterion("upper(REG_ADDRESS) like", value.toUpperCase(), "regAddress");
            return (Criteria) this;
        }

        public Criteria andAddressLikeInsensitive(String value) {
            addCriterion("upper(ADDRESS) like", value.toUpperCase(), "address");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLikeInsensitive(String value) {
            addCriterion("upper(ADDRESS_POSTCODE) like", value.toUpperCase(), "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andBusinessScopeLikeInsensitive(String value) {
            addCriterion("upper(BUSINESS_SCOPE) like", value.toUpperCase(), "businessScope");
            return (Criteria) this;
        }

        public Criteria andChairmanLikeInsensitive(String value) {
            addCriterion("upper(CHAIRMAN) like", value.toUpperCase(), "chairman");
            return (Criteria) this;
        }

        public Criteria andIndedirectorsLikeInsensitive(String value) {
            addCriterion("upper(INDEDIRECTORS) like", value.toUpperCase(), "indedirectors");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLikeInsensitive(String value) {
            addCriterion("upper(LEGAL_PERSON) like", value.toUpperCase(), "legalPerson");
            return (Criteria) this;
        }

        public Criteria andRegNumLikeInsensitive(String value) {
            addCriterion("upper(REG_NUM) like", value.toUpperCase(), "regNum");
            return (Criteria) this;
        }

        public Criteria andSecucodeLikeInsensitive(String value) {
            addCriterion("upper(SECUCODE) like", value.toUpperCase(), "secucode");
            return (Criteria) this;
        }

        public Criteria andSecurityTypeLikeInsensitive(String value) {
            addCriterion("upper(SECURITY_TYPE) like", value.toUpperCase(), "securityType");
            return (Criteria) this;
        }

        public Criteria andNationLikeInsensitive(String value) {
            addCriterion("upper(NATION) like", value.toUpperCase(), "nation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 16 19:42:04 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_info
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}