package org.whatever.stockspider.db.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DayPriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    protected int offset;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    protected int limit;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    protected String sumCol;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    protected String groupSelClause;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public DayPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public void setOffset(int offset) {
         this.offset = offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public int getOffset() {
          return offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public void setLimit(int limit) {
         this.limit = limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    *
    * @generated Tue Apr 16 19:42:04 CST 2024
    */
    public int getLimit() {
          return limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    public String getSumCol() {
          return sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    public String getGroupSelClause() {
          return groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table day_price
    */
    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTradingDateIsNull() {
            addCriterion("TRADING_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTradingDateIsNotNull() {
            addCriterion("TRADING_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTradingDateEqualTo(Date value) {
            addCriterionForJDBCDate("TRADING_DATE =", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("TRADING_DATE <>", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateGreaterThan(Date value) {
            addCriterionForJDBCDate("TRADING_DATE >", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TRADING_DATE >=", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateLessThan(Date value) {
            addCriterionForJDBCDate("TRADING_DATE <", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TRADING_DATE <=", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateIn(List<Date> values) {
            addCriterionForJDBCDate("TRADING_DATE in", values, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("TRADING_DATE not in", values, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TRADING_DATE between", value1, value2, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TRADING_DATE not between", value1, value2, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceIsNull() {
            addCriterion("OPENING_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceIsNotNull() {
            addCriterion("OPENING_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceEqualTo(BigDecimal value) {
            addCriterion("OPENING_PRICE =", value, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceNotEqualTo(BigDecimal value) {
            addCriterion("OPENING_PRICE <>", value, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceGreaterThan(BigDecimal value) {
            addCriterion("OPENING_PRICE >", value, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OPENING_PRICE >=", value, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceLessThan(BigDecimal value) {
            addCriterion("OPENING_PRICE <", value, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OPENING_PRICE <=", value, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceIn(List<BigDecimal> values) {
            addCriterion("OPENING_PRICE in", values, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceNotIn(List<BigDecimal> values) {
            addCriterion("OPENING_PRICE not in", values, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OPENING_PRICE between", value1, value2, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andOpeningPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OPENING_PRICE not between", value1, value2, "openingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceIsNull() {
            addCriterion("CLOSING_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andClosingPriceIsNotNull() {
            addCriterion("CLOSING_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andClosingPriceEqualTo(BigDecimal value) {
            addCriterion("CLOSING_PRICE =", value, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceNotEqualTo(BigDecimal value) {
            addCriterion("CLOSING_PRICE <>", value, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceGreaterThan(BigDecimal value) {
            addCriterion("CLOSING_PRICE >", value, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CLOSING_PRICE >=", value, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceLessThan(BigDecimal value) {
            addCriterion("CLOSING_PRICE <", value, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CLOSING_PRICE <=", value, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceIn(List<BigDecimal> values) {
            addCriterion("CLOSING_PRICE in", values, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceNotIn(List<BigDecimal> values) {
            addCriterion("CLOSING_PRICE not in", values, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLOSING_PRICE between", value1, value2, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andClosingPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLOSING_PRICE not between", value1, value2, "closingPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceIsNull() {
            addCriterion("PEAK_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPeakPriceIsNotNull() {
            addCriterion("PEAK_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPeakPriceEqualTo(BigDecimal value) {
            addCriterion("PEAK_PRICE =", value, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceNotEqualTo(BigDecimal value) {
            addCriterion("PEAK_PRICE <>", value, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceGreaterThan(BigDecimal value) {
            addCriterion("PEAK_PRICE >", value, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PEAK_PRICE >=", value, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceLessThan(BigDecimal value) {
            addCriterion("PEAK_PRICE <", value, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PEAK_PRICE <=", value, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceIn(List<BigDecimal> values) {
            addCriterion("PEAK_PRICE in", values, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceNotIn(List<BigDecimal> values) {
            addCriterion("PEAK_PRICE not in", values, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PEAK_PRICE between", value1, value2, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andPeakPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PEAK_PRICE not between", value1, value2, "peakPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceIsNull() {
            addCriterion("BOTTOM_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andBottomPriceIsNotNull() {
            addCriterion("BOTTOM_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andBottomPriceEqualTo(BigDecimal value) {
            addCriterion("BOTTOM_PRICE =", value, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceNotEqualTo(BigDecimal value) {
            addCriterion("BOTTOM_PRICE <>", value, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceGreaterThan(BigDecimal value) {
            addCriterion("BOTTOM_PRICE >", value, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BOTTOM_PRICE >=", value, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceLessThan(BigDecimal value) {
            addCriterion("BOTTOM_PRICE <", value, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BOTTOM_PRICE <=", value, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceIn(List<BigDecimal> values) {
            addCriterion("BOTTOM_PRICE in", values, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceNotIn(List<BigDecimal> values) {
            addCriterion("BOTTOM_PRICE not in", values, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BOTTOM_PRICE between", value1, value2, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andBottomPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BOTTOM_PRICE not between", value1, value2, "bottomPrice");
            return (Criteria) this;
        }

        public Criteria andChangeRateIsNull() {
            addCriterion("CHANGE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andChangeRateIsNotNull() {
            addCriterion("CHANGE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andChangeRateEqualTo(BigDecimal value) {
            addCriterion("CHANGE_RATE =", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateNotEqualTo(BigDecimal value) {
            addCriterion("CHANGE_RATE <>", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateGreaterThan(BigDecimal value) {
            addCriterion("CHANGE_RATE >", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANGE_RATE >=", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateLessThan(BigDecimal value) {
            addCriterion("CHANGE_RATE <", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANGE_RATE <=", value, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateIn(List<BigDecimal> values) {
            addCriterion("CHANGE_RATE in", values, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateNotIn(List<BigDecimal> values) {
            addCriterion("CHANGE_RATE not in", values, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANGE_RATE between", value1, value2, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANGE_RATE not between", value1, value2, "changeRate");
            return (Criteria) this;
        }

        public Criteria andChangeAmountIsNull() {
            addCriterion("CHANGE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andChangeAmountIsNotNull() {
            addCriterion("CHANGE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andChangeAmountEqualTo(BigDecimal value) {
            addCriterion("CHANGE_AMOUNT =", value, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountNotEqualTo(BigDecimal value) {
            addCriterion("CHANGE_AMOUNT <>", value, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountGreaterThan(BigDecimal value) {
            addCriterion("CHANGE_AMOUNT >", value, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANGE_AMOUNT >=", value, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountLessThan(BigDecimal value) {
            addCriterion("CHANGE_AMOUNT <", value, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANGE_AMOUNT <=", value, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountIn(List<BigDecimal> values) {
            addCriterion("CHANGE_AMOUNT in", values, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountNotIn(List<BigDecimal> values) {
            addCriterion("CHANGE_AMOUNT not in", values, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANGE_AMOUNT between", value1, value2, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andChangeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANGE_AMOUNT not between", value1, value2, "changeAmount");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeIsNull() {
            addCriterion("TRADING_VOLUME is null");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeIsNotNull() {
            addCriterion("TRADING_VOLUME is not null");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeEqualTo(Integer value) {
            addCriterion("TRADING_VOLUME =", value, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeNotEqualTo(Integer value) {
            addCriterion("TRADING_VOLUME <>", value, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeGreaterThan(Integer value) {
            addCriterion("TRADING_VOLUME >", value, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TRADING_VOLUME >=", value, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeLessThan(Integer value) {
            addCriterion("TRADING_VOLUME <", value, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeLessThanOrEqualTo(Integer value) {
            addCriterion("TRADING_VOLUME <=", value, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeIn(List<Integer> values) {
            addCriterion("TRADING_VOLUME in", values, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeNotIn(List<Integer> values) {
            addCriterion("TRADING_VOLUME not in", values, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeBetween(Integer value1, Integer value2) {
            addCriterion("TRADING_VOLUME between", value1, value2, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingVolumeNotBetween(Integer value1, Integer value2) {
            addCriterion("TRADING_VOLUME not between", value1, value2, "tradingVolume");
            return (Criteria) this;
        }

        public Criteria andTradingAmountIsNull() {
            addCriterion("TRADING_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andTradingAmountIsNotNull() {
            addCriterion("TRADING_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andTradingAmountEqualTo(BigDecimal value) {
            addCriterion("TRADING_AMOUNT =", value, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountNotEqualTo(BigDecimal value) {
            addCriterion("TRADING_AMOUNT <>", value, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountGreaterThan(BigDecimal value) {
            addCriterion("TRADING_AMOUNT >", value, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADING_AMOUNT >=", value, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountLessThan(BigDecimal value) {
            addCriterion("TRADING_AMOUNT <", value, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRADING_AMOUNT <=", value, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountIn(List<BigDecimal> values) {
            addCriterion("TRADING_AMOUNT in", values, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountNotIn(List<BigDecimal> values) {
            addCriterion("TRADING_AMOUNT not in", values, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADING_AMOUNT between", value1, value2, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andTradingAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRADING_AMOUNT not between", value1, value2, "tradingAmount");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateIsNull() {
            addCriterion("AMPLITUDE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateIsNotNull() {
            addCriterion("AMPLITUDE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateEqualTo(BigDecimal value) {
            addCriterion("AMPLITUDE_RATE =", value, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateNotEqualTo(BigDecimal value) {
            addCriterion("AMPLITUDE_RATE <>", value, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateGreaterThan(BigDecimal value) {
            addCriterion("AMPLITUDE_RATE >", value, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMPLITUDE_RATE >=", value, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateLessThan(BigDecimal value) {
            addCriterion("AMPLITUDE_RATE <", value, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMPLITUDE_RATE <=", value, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateIn(List<BigDecimal> values) {
            addCriterion("AMPLITUDE_RATE in", values, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateNotIn(List<BigDecimal> values) {
            addCriterion("AMPLITUDE_RATE not in", values, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMPLITUDE_RATE between", value1, value2, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andAmplitudeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMPLITUDE_RATE not between", value1, value2, "amplitudeRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateIsNull() {
            addCriterion("TURNOVER_RATE is null");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateIsNotNull() {
            addCriterion("TURNOVER_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateEqualTo(BigDecimal value) {
            addCriterion("TURNOVER_RATE =", value, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateNotEqualTo(BigDecimal value) {
            addCriterion("TURNOVER_RATE <>", value, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateGreaterThan(BigDecimal value) {
            addCriterion("TURNOVER_RATE >", value, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TURNOVER_RATE >=", value, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateLessThan(BigDecimal value) {
            addCriterion("TURNOVER_RATE <", value, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TURNOVER_RATE <=", value, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateIn(List<BigDecimal> values) {
            addCriterion("TURNOVER_RATE in", values, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateNotIn(List<BigDecimal> values) {
            addCriterion("TURNOVER_RATE not in", values, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TURNOVER_RATE between", value1, value2, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andTurnoverRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TURNOVER_RATE not between", value1, value2, "turnoverRate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("GMT_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("GMT_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("GMT_MODIFIED =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("GMT_MODIFIED >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("GMT_MODIFIED <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("GMT_MODIFIED in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("GMT_MODIFIED not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(CODE) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(NAME) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table day_price
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 16 19:42:04 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}