package org.whatever.stockspider.db.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DayPrice extends DayPriceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.CODE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.NAME
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.TRADING_DATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private Date tradingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.OPENING_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal openingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.CLOSING_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal closingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.PEAK_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal peakPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.BOTTOM_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal bottomPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.CHANGE_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal changeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.CHANGE_AMOUNT
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal changeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.TRADING_VOLUME
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private Integer tradingVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.TRADING_AMOUNT
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal tradingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.AMPLITUDE_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal amplitudeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.TURNOVER_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private BigDecimal turnoverRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.GMT_CREATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_price.GMT_MODIFIED
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.CODE
     *
     * @return the value of day_price.CODE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.CODE
     *
     * @param code the value for day_price.CODE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.NAME
     *
     * @return the value of day_price.NAME
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.NAME
     *
     * @param name the value for day_price.NAME
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.TRADING_DATE
     *
     * @return the value of day_price.TRADING_DATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Date getTradingDate() {
        return tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.TRADING_DATE
     *
     * @param tradingDate the value for day_price.TRADING_DATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setTradingDate(Date tradingDate) {
        this.tradingDate = tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.OPENING_PRICE
     *
     * @return the value of day_price.OPENING_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getOpeningPrice() {
        return openingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.OPENING_PRICE
     *
     * @param openingPrice the value for day_price.OPENING_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setOpeningPrice(BigDecimal openingPrice) {
        this.openingPrice = openingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.CLOSING_PRICE
     *
     * @return the value of day_price.CLOSING_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getClosingPrice() {
        return closingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.CLOSING_PRICE
     *
     * @param closingPrice the value for day_price.CLOSING_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setClosingPrice(BigDecimal closingPrice) {
        this.closingPrice = closingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.PEAK_PRICE
     *
     * @return the value of day_price.PEAK_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getPeakPrice() {
        return peakPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.PEAK_PRICE
     *
     * @param peakPrice the value for day_price.PEAK_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setPeakPrice(BigDecimal peakPrice) {
        this.peakPrice = peakPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.BOTTOM_PRICE
     *
     * @return the value of day_price.BOTTOM_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getBottomPrice() {
        return bottomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.BOTTOM_PRICE
     *
     * @param bottomPrice the value for day_price.BOTTOM_PRICE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setBottomPrice(BigDecimal bottomPrice) {
        this.bottomPrice = bottomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.CHANGE_RATE
     *
     * @return the value of day_price.CHANGE_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getChangeRate() {
        return changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.CHANGE_RATE
     *
     * @param changeRate the value for day_price.CHANGE_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setChangeRate(BigDecimal changeRate) {
        this.changeRate = changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.CHANGE_AMOUNT
     *
     * @return the value of day_price.CHANGE_AMOUNT
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getChangeAmount() {
        return changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.CHANGE_AMOUNT
     *
     * @param changeAmount the value for day_price.CHANGE_AMOUNT
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setChangeAmount(BigDecimal changeAmount) {
        this.changeAmount = changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.TRADING_VOLUME
     *
     * @return the value of day_price.TRADING_VOLUME
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Integer getTradingVolume() {
        return tradingVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.TRADING_VOLUME
     *
     * @param tradingVolume the value for day_price.TRADING_VOLUME
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setTradingVolume(Integer tradingVolume) {
        this.tradingVolume = tradingVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.TRADING_AMOUNT
     *
     * @return the value of day_price.TRADING_AMOUNT
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getTradingAmount() {
        return tradingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.TRADING_AMOUNT
     *
     * @param tradingAmount the value for day_price.TRADING_AMOUNT
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setTradingAmount(BigDecimal tradingAmount) {
        this.tradingAmount = tradingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.AMPLITUDE_RATE
     *
     * @return the value of day_price.AMPLITUDE_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getAmplitudeRate() {
        return amplitudeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.AMPLITUDE_RATE
     *
     * @param amplitudeRate the value for day_price.AMPLITUDE_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setAmplitudeRate(BigDecimal amplitudeRate) {
        this.amplitudeRate = amplitudeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.TURNOVER_RATE
     *
     * @return the value of day_price.TURNOVER_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public BigDecimal getTurnoverRate() {
        return turnoverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.TURNOVER_RATE
     *
     * @param turnoverRate the value for day_price.TURNOVER_RATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setTurnoverRate(BigDecimal turnoverRate) {
        this.turnoverRate = turnoverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.GMT_CREATE
     *
     * @return the value of day_price.GMT_CREATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.GMT_CREATE
     *
     * @param gmtCreate the value for day_price.GMT_CREATE
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_price.GMT_MODIFIED
     *
     * @return the value of day_price.GMT_MODIFIED
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_price.GMT_MODIFIED
     *
     * @param gmtModified the value for day_price.GMT_MODIFIED
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DayPrice other = (DayPrice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTradingDate() == null ? other.getTradingDate() == null : this.getTradingDate().equals(other.getTradingDate()))
            && (this.getOpeningPrice() == null ? other.getOpeningPrice() == null : this.getOpeningPrice().equals(other.getOpeningPrice()))
            && (this.getClosingPrice() == null ? other.getClosingPrice() == null : this.getClosingPrice().equals(other.getClosingPrice()))
            && (this.getPeakPrice() == null ? other.getPeakPrice() == null : this.getPeakPrice().equals(other.getPeakPrice()))
            && (this.getBottomPrice() == null ? other.getBottomPrice() == null : this.getBottomPrice().equals(other.getBottomPrice()))
            && (this.getChangeRate() == null ? other.getChangeRate() == null : this.getChangeRate().equals(other.getChangeRate()))
            && (this.getChangeAmount() == null ? other.getChangeAmount() == null : this.getChangeAmount().equals(other.getChangeAmount()))
            && (this.getTradingVolume() == null ? other.getTradingVolume() == null : this.getTradingVolume().equals(other.getTradingVolume()))
            && (this.getTradingAmount() == null ? other.getTradingAmount() == null : this.getTradingAmount().equals(other.getTradingAmount()))
            && (this.getAmplitudeRate() == null ? other.getAmplitudeRate() == null : this.getAmplitudeRate().equals(other.getAmplitudeRate()))
            && (this.getTurnoverRate() == null ? other.getTurnoverRate() == null : this.getTurnoverRate().equals(other.getTurnoverRate()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTradingDate() == null) ? 0 : getTradingDate().hashCode());
        result = prime * result + ((getOpeningPrice() == null) ? 0 : getOpeningPrice().hashCode());
        result = prime * result + ((getClosingPrice() == null) ? 0 : getClosingPrice().hashCode());
        result = prime * result + ((getPeakPrice() == null) ? 0 : getPeakPrice().hashCode());
        result = prime * result + ((getBottomPrice() == null) ? 0 : getBottomPrice().hashCode());
        result = prime * result + ((getChangeRate() == null) ? 0 : getChangeRate().hashCode());
        result = prime * result + ((getChangeAmount() == null) ? 0 : getChangeAmount().hashCode());
        result = prime * result + ((getTradingVolume() == null) ? 0 : getTradingVolume().hashCode());
        result = prime * result + ((getTradingAmount() == null) ? 0 : getTradingAmount().hashCode());
        result = prime * result + ((getAmplitudeRate() == null) ? 0 : getAmplitudeRate().hashCode());
        result = prime * result + ((getTurnoverRate() == null) ? 0 : getTurnoverRate().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", tradingDate=").append(tradingDate);
        sb.append(", openingPrice=").append(openingPrice);
        sb.append(", closingPrice=").append(closingPrice);
        sb.append(", peakPrice=").append(peakPrice);
        sb.append(", bottomPrice=").append(bottomPrice);
        sb.append(", changeRate=").append(changeRate);
        sb.append(", changeAmount=").append(changeAmount);
        sb.append(", tradingVolume=").append(tradingVolume);
        sb.append(", tradingAmount=").append(tradingAmount);
        sb.append(", amplitudeRate=").append(amplitudeRate);
        sb.append(", turnoverRate=").append(turnoverRate);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}