package org.whatever.stockspider.db.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FailRetryRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    *
    * @generated Mon Apr 17 10:21:38 CST 2024
    */
    protected int offset;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    *
    * @generated Mon Apr 17 10:21:38 CST 2024
    */
    protected int limit;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    protected String sumCol;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    protected String groupSelClause;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public FailRetryRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    *
    * @generated Mon Apr 17 10:21:38 CST 2024
    */
    public void setOffset(int offset) {
         this.offset = offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    *
    * @generated Mon Apr 17 10:21:38 CST 2024
    */
    public int getOffset() {
          return offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    *
    * @generated Mon Apr 17 10:21:38 CST 2024
    */
    public void setLimit(int limit) {
         this.limit = limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    *
    * @generated Mon Apr 17 10:21:38 CST 2024
    */
    public int getLimit() {
          return limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    public String getSumCol() {
          return sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    public String getGroupSelClause() {
          return groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table fail_retry_record
    */
    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTradingDateIsNull() {
            addCriterion("TRADING_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTradingDateIsNotNull() {
            addCriterion("TRADING_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTradingDateEqualTo(String value) {
            addCriterion("TRADING_DATE =", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateNotEqualTo(String value) {
            addCriterion("TRADING_DATE <>", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateGreaterThan(String value) {
            addCriterion("TRADING_DATE >", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateGreaterThanOrEqualTo(String value) {
            addCriterion("TRADING_DATE >=", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateLessThan(String value) {
            addCriterion("TRADING_DATE <", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateLessThanOrEqualTo(String value) {
            addCriterion("TRADING_DATE <=", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateLike(String value) {
            addCriterion("TRADING_DATE like", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateNotLike(String value) {
            addCriterion("TRADING_DATE not like", value, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateIn(List<String> values) {
            addCriterion("TRADING_DATE in", values, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateNotIn(List<String> values) {
            addCriterion("TRADING_DATE not in", values, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateBetween(String value1, String value2) {
            addCriterion("TRADING_DATE between", value1, value2, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andTradingDateNotBetween(String value1, String value2) {
            addCriterion("TRADING_DATE not between", value1, value2, "tradingDate");
            return (Criteria) this;
        }

        public Criteria andFailTypeIsNull() {
            addCriterion("FAIL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFailTypeIsNotNull() {
            addCriterion("FAIL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFailTypeEqualTo(String value) {
            addCriterion("FAIL_TYPE =", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeNotEqualTo(String value) {
            addCriterion("FAIL_TYPE <>", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeGreaterThan(String value) {
            addCriterion("FAIL_TYPE >", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FAIL_TYPE >=", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeLessThan(String value) {
            addCriterion("FAIL_TYPE <", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeLessThanOrEqualTo(String value) {
            addCriterion("FAIL_TYPE <=", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeLike(String value) {
            addCriterion("FAIL_TYPE like", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeNotLike(String value) {
            addCriterion("FAIL_TYPE not like", value, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeIn(List<String> values) {
            addCriterion("FAIL_TYPE in", values, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeNotIn(List<String> values) {
            addCriterion("FAIL_TYPE not in", values, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeBetween(String value1, String value2) {
            addCriterion("FAIL_TYPE between", value1, value2, "failType");
            return (Criteria) this;
        }

        public Criteria andFailTypeNotBetween(String value1, String value2) {
            addCriterion("FAIL_TYPE not between", value1, value2, "failType");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesIsNull() {
            addCriterion("RETRY_SUCCES is null");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesIsNotNull() {
            addCriterion("RETRY_SUCCES is not null");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesEqualTo(Integer value) {
            addCriterion("RETRY_SUCCES =", value, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesNotEqualTo(Integer value) {
            addCriterion("RETRY_SUCCES <>", value, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesGreaterThan(Integer value) {
            addCriterion("RETRY_SUCCES >", value, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesGreaterThanOrEqualTo(Integer value) {
            addCriterion("RETRY_SUCCES >=", value, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesLessThan(Integer value) {
            addCriterion("RETRY_SUCCES <", value, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesLessThanOrEqualTo(Integer value) {
            addCriterion("RETRY_SUCCES <=", value, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesIn(List<Integer> values) {
            addCriterion("RETRY_SUCCES in", values, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesNotIn(List<Integer> values) {
            addCriterion("RETRY_SUCCES not in", values, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesBetween(Integer value1, Integer value2) {
            addCriterion("RETRY_SUCCES between", value1, value2, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andRetrySuccesNotBetween(Integer value1, Integer value2) {
            addCriterion("RETRY_SUCCES not between", value1, value2, "retrySucces");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("GMT_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("GMT_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("GMT_MODIFIED =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("GMT_MODIFIED >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("GMT_MODIFIED <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("GMT_MODIFIED in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("GMT_MODIFIED not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(CODE) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(NAME) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andTradingDateLikeInsensitive(String value) {
            addCriterion("upper(TRADING_DATE) like", value.toUpperCase(), "tradingDate");
            return (Criteria) this;
        }

        public Criteria andFailTypeLikeInsensitive(String value) {
            addCriterion("upper(FAIL_TYPE) like", value.toUpperCase(), "failType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fail_retry_record
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 22 10:21:38 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}