package org.whatever.stockspider.db.entity;

import lombok.NonNull;

public class FailRetryRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_retry_record.ID
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    @NonNull
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_retry_record.ID
     *
     * @return the value of fail_retry_record.ID
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_retry_record.ID
     *
     * @param id the value for fail_retry_record.ID
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FailRetryRecordKey other = (FailRetryRecordKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append("]");
        return sb.toString();
    }
}