package org.whatever.stockspider.db.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockDividendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    *
    * @generated Tue Apr 17 11:18:21 CST 2024
    */
    protected int offset;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    *
    * @generated Tue Apr 17 11:18:21 CST 2024
    */
    protected int limit;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    protected String sumCol;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    protected String groupSelClause;

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public StockDividendExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    *
    * @generated Tue Apr 17 11:18:21 CST 2024
    */
    public void setOffset(int offset) {
         this.offset = offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    *
    * @generated Tue Apr 17 11:18:21 CST 2024
    */
    public int getOffset() {
          return offset;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    *
    * @generated Tue Apr 17 11:18:21 CST 2024
    */
    public void setLimit(int limit) {
         this.limit = limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    *
    * @generated Tue Apr 17 11:18:21 CST 2024
    */
    public int getLimit() {
          return limit;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    public String getSumCol() {
          return sumCol;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    public String getGroupSelClause() {
          return groupSelClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table stock_dividend
    */
    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileIsNull() {
            addCriterion("IMPL_PLAN_PROFILE is null");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileIsNotNull() {
            addCriterion("IMPL_PLAN_PROFILE is not null");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileEqualTo(String value) {
            addCriterion("IMPL_PLAN_PROFILE =", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileNotEqualTo(String value) {
            addCriterion("IMPL_PLAN_PROFILE <>", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileGreaterThan(String value) {
            addCriterion("IMPL_PLAN_PROFILE >", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileGreaterThanOrEqualTo(String value) {
            addCriterion("IMPL_PLAN_PROFILE >=", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileLessThan(String value) {
            addCriterion("IMPL_PLAN_PROFILE <", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileLessThanOrEqualTo(String value) {
            addCriterion("IMPL_PLAN_PROFILE <=", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileLike(String value) {
            addCriterion("IMPL_PLAN_PROFILE like", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileNotLike(String value) {
            addCriterion("IMPL_PLAN_PROFILE not like", value, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileIn(List<String> values) {
            addCriterion("IMPL_PLAN_PROFILE in", values, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileNotIn(List<String> values) {
            addCriterion("IMPL_PLAN_PROFILE not in", values, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileBetween(String value1, String value2) {
            addCriterion("IMPL_PLAN_PROFILE between", value1, value2, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileNotBetween(String value1, String value2) {
            addCriterion("IMPL_PLAN_PROFILE not between", value1, value2, "implPlanProfile");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateIsNull() {
            addCriterion("EQUITY_RECORD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateIsNotNull() {
            addCriterion("EQUITY_RECORD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateEqualTo(Date value) {
            addCriterion("EQUITY_RECORD_DATE =", value, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateNotEqualTo(Date value) {
            addCriterion("EQUITY_RECORD_DATE <>", value, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateGreaterThan(Date value) {
            addCriterion("EQUITY_RECORD_DATE >", value, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EQUITY_RECORD_DATE >=", value, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateLessThan(Date value) {
            addCriterion("EQUITY_RECORD_DATE <", value, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateLessThanOrEqualTo(Date value) {
            addCriterion("EQUITY_RECORD_DATE <=", value, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateIn(List<Date> values) {
            addCriterion("EQUITY_RECORD_DATE in", values, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateNotIn(List<Date> values) {
            addCriterion("EQUITY_RECORD_DATE not in", values, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateBetween(Date value1, Date value2) {
            addCriterion("EQUITY_RECORD_DATE between", value1, value2, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andEquityRecordDateNotBetween(Date value1, Date value2) {
            addCriterion("EQUITY_RECORD_DATE not between", value1, value2, "equityRecordDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateIsNull() {
            addCriterion("EX_DIVIDEND_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExDividendDateIsNotNull() {
            addCriterion("EX_DIVIDEND_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExDividendDateEqualTo(Date value) {
            addCriterion("EX_DIVIDEND_DATE =", value, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateNotEqualTo(Date value) {
            addCriterion("EX_DIVIDEND_DATE <>", value, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateGreaterThan(Date value) {
            addCriterion("EX_DIVIDEND_DATE >", value, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EX_DIVIDEND_DATE >=", value, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateLessThan(Date value) {
            addCriterion("EX_DIVIDEND_DATE <", value, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateLessThanOrEqualTo(Date value) {
            addCriterion("EX_DIVIDEND_DATE <=", value, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateIn(List<Date> values) {
            addCriterion("EX_DIVIDEND_DATE in", values, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateNotIn(List<Date> values) {
            addCriterion("EX_DIVIDEND_DATE not in", values, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateBetween(Date value1, Date value2) {
            addCriterion("EX_DIVIDEND_DATE between", value1, value2, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andExDividendDateNotBetween(Date value1, Date value2) {
            addCriterion("EX_DIVIDEND_DATE not between", value1, value2, "exDividendDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateIsNull() {
            addCriterion("NOTICE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andNoticeDateIsNotNull() {
            addCriterion("NOTICE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeDateEqualTo(Date value) {
            addCriterion("NOTICE_DATE =", value, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateNotEqualTo(Date value) {
            addCriterion("NOTICE_DATE <>", value, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateGreaterThan(Date value) {
            addCriterion("NOTICE_DATE >", value, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("NOTICE_DATE >=", value, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateLessThan(Date value) {
            addCriterion("NOTICE_DATE <", value, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateLessThanOrEqualTo(Date value) {
            addCriterion("NOTICE_DATE <=", value, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateIn(List<Date> values) {
            addCriterion("NOTICE_DATE in", values, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateNotIn(List<Date> values) {
            addCriterion("NOTICE_DATE not in", values, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateBetween(Date value1, Date value2) {
            addCriterion("NOTICE_DATE between", value1, value2, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andNoticeDateNotBetween(Date value1, Date value2) {
            addCriterion("NOTICE_DATE not between", value1, value2, "noticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateIsNull() {
            addCriterion("PLAN_NOTICE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateIsNotNull() {
            addCriterion("PLAN_NOTICE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateEqualTo(Date value) {
            addCriterion("PLAN_NOTICE_DATE =", value, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateNotEqualTo(Date value) {
            addCriterion("PLAN_NOTICE_DATE <>", value, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateGreaterThan(Date value) {
            addCriterion("PLAN_NOTICE_DATE >", value, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PLAN_NOTICE_DATE >=", value, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateLessThan(Date value) {
            addCriterion("PLAN_NOTICE_DATE <", value, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateLessThanOrEqualTo(Date value) {
            addCriterion("PLAN_NOTICE_DATE <=", value, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateIn(List<Date> values) {
            addCriterion("PLAN_NOTICE_DATE in", values, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateNotIn(List<Date> values) {
            addCriterion("PLAN_NOTICE_DATE not in", values, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateBetween(Date value1, Date value2) {
            addCriterion("PLAN_NOTICE_DATE between", value1, value2, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPlanNoticeDateNotBetween(Date value1, Date value2) {
            addCriterion("PLAN_NOTICE_DATE not between", value1, value2, "planNoticeDate");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbIsNull() {
            addCriterion("PRETAX_BONUS_RMB is null");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbIsNotNull() {
            addCriterion("PRETAX_BONUS_RMB is not null");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbEqualTo(BigDecimal value) {
            addCriterion("PRETAX_BONUS_RMB =", value, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbNotEqualTo(BigDecimal value) {
            addCriterion("PRETAX_BONUS_RMB <>", value, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbGreaterThan(BigDecimal value) {
            addCriterion("PRETAX_BONUS_RMB >", value, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRETAX_BONUS_RMB >=", value, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbLessThan(BigDecimal value) {
            addCriterion("PRETAX_BONUS_RMB <", value, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRETAX_BONUS_RMB <=", value, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbIn(List<BigDecimal> values) {
            addCriterion("PRETAX_BONUS_RMB in", values, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbNotIn(List<BigDecimal> values) {
            addCriterion("PRETAX_BONUS_RMB not in", values, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRETAX_BONUS_RMB between", value1, value2, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andPretaxBonusRmbNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRETAX_BONUS_RMB not between", value1, value2, "pretaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbIsNull() {
            addCriterion("AFTERTAX_BONUS_RMB is null");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbIsNotNull() {
            addCriterion("AFTERTAX_BONUS_RMB is not null");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbEqualTo(BigDecimal value) {
            addCriterion("AFTERTAX_BONUS_RMB =", value, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbNotEqualTo(BigDecimal value) {
            addCriterion("AFTERTAX_BONUS_RMB <>", value, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbGreaterThan(BigDecimal value) {
            addCriterion("AFTERTAX_BONUS_RMB >", value, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AFTERTAX_BONUS_RMB >=", value, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbLessThan(BigDecimal value) {
            addCriterion("AFTERTAX_BONUS_RMB <", value, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AFTERTAX_BONUS_RMB <=", value, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbIn(List<BigDecimal> values) {
            addCriterion("AFTERTAX_BONUS_RMB in", values, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbNotIn(List<BigDecimal> values) {
            addCriterion("AFTERTAX_BONUS_RMB not in", values, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AFTERTAX_BONUS_RMB between", value1, value2, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andAftertaxBonusRmbNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AFTERTAX_BONUS_RMB not between", value1, value2, "aftertaxBonusRmb");
            return (Criteria) this;
        }

        public Criteria andBaseShareIsNull() {
            addCriterion("BASE_SHARE is null");
            return (Criteria) this;
        }

        public Criteria andBaseShareIsNotNull() {
            addCriterion("BASE_SHARE is not null");
            return (Criteria) this;
        }

        public Criteria andBaseShareEqualTo(Integer value) {
            addCriterion("BASE_SHARE =", value, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareNotEqualTo(Integer value) {
            addCriterion("BASE_SHARE <>", value, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareGreaterThan(Integer value) {
            addCriterion("BASE_SHARE >", value, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareGreaterThanOrEqualTo(Integer value) {
            addCriterion("BASE_SHARE >=", value, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareLessThan(Integer value) {
            addCriterion("BASE_SHARE <", value, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareLessThanOrEqualTo(Integer value) {
            addCriterion("BASE_SHARE <=", value, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareIn(List<Integer> values) {
            addCriterion("BASE_SHARE in", values, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareNotIn(List<Integer> values) {
            addCriterion("BASE_SHARE not in", values, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareBetween(Integer value1, Integer value2) {
            addCriterion("BASE_SHARE between", value1, value2, "baseShare");
            return (Criteria) this;
        }

        public Criteria andBaseShareNotBetween(Integer value1, Integer value2) {
            addCriterion("BASE_SHARE not between", value1, value2, "baseShare");
            return (Criteria) this;
        }

        public Criteria andHandselIsNull() {
            addCriterion("HANDSEL is null");
            return (Criteria) this;
        }

        public Criteria andHandselIsNotNull() {
            addCriterion("HANDSEL is not null");
            return (Criteria) this;
        }

        public Criteria andHandselEqualTo(BigDecimal value) {
            addCriterion("HANDSEL =", value, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselNotEqualTo(BigDecimal value) {
            addCriterion("HANDSEL <>", value, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselGreaterThan(BigDecimal value) {
            addCriterion("HANDSEL >", value, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HANDSEL >=", value, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselLessThan(BigDecimal value) {
            addCriterion("HANDSEL <", value, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HANDSEL <=", value, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselIn(List<BigDecimal> values) {
            addCriterion("HANDSEL in", values, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselNotIn(List<BigDecimal> values) {
            addCriterion("HANDSEL not in", values, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HANDSEL between", value1, value2, "handsel");
            return (Criteria) this;
        }

        public Criteria andHandselNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HANDSEL not between", value1, value2, "handsel");
            return (Criteria) this;
        }

        public Criteria andTransferIsNull() {
            addCriterion("TRANSFER is null");
            return (Criteria) this;
        }

        public Criteria andTransferIsNotNull() {
            addCriterion("TRANSFER is not null");
            return (Criteria) this;
        }

        public Criteria andTransferEqualTo(BigDecimal value) {
            addCriterion("TRANSFER =", value, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferNotEqualTo(BigDecimal value) {
            addCriterion("TRANSFER <>", value, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferGreaterThan(BigDecimal value) {
            addCriterion("TRANSFER >", value, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANSFER >=", value, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferLessThan(BigDecimal value) {
            addCriterion("TRANSFER <", value, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRANSFER <=", value, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferIn(List<BigDecimal> values) {
            addCriterion("TRANSFER in", values, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferNotIn(List<BigDecimal> values) {
            addCriterion("TRANSFER not in", values, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANSFER between", value1, value2, "transfer");
            return (Criteria) this;
        }

        public Criteria andTransferNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRANSFER not between", value1, value2, "transfer");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("GMT_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("GMT_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("GMT_MODIFIED =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("GMT_MODIFIED >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("GMT_MODIFIED <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIED <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("GMT_MODIFIED in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("GMT_MODIFIED not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIED not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(CODE) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(NAME) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andImplPlanProfileLikeInsensitive(String value) {
            addCriterion("upper(IMPL_PLAN_PROFILE) like", value.toUpperCase(), "implPlanProfile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_dividend
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 23 11:18:21 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}