package org.whatever.stockspider.db.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.whatever.stockspider.db.entity.DayPrice;
import org.whatever.stockspider.db.entity.DayPriceExample.Criteria;
import org.whatever.stockspider.db.entity.DayPriceExample.Criterion;
import org.whatever.stockspider.db.entity.DayPriceExample;

public class DayPriceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String countByExample(DayPriceExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("day_price");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String deleteByExample(DayPriceExample example) {
        BEGIN();
        DELETE_FROM("day_price");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String insertSelective(DayPrice record) {
        BEGIN();
        INSERT_INTO("day_price");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getCode() != null) {
            VALUES("CODE", "#{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("NAME", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTradingDate() != null) {
            VALUES("TRADING_DATE", "#{tradingDate,jdbcType=DATE}");
        }
        
        if (record.getOpeningPrice() != null) {
            VALUES("OPENING_PRICE", "#{openingPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getClosingPrice() != null) {
            VALUES("CLOSING_PRICE", "#{closingPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPeakPrice() != null) {
            VALUES("PEAK_PRICE", "#{peakPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getBottomPrice() != null) {
            VALUES("BOTTOM_PRICE", "#{bottomPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getChangeRate() != null) {
            VALUES("CHANGE_RATE", "#{changeRate,jdbcType=DECIMAL}");
        }
        
        if (record.getChangeAmount() != null) {
            VALUES("CHANGE_AMOUNT", "#{changeAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getTradingVolume() != null) {
            VALUES("TRADING_VOLUME", "#{tradingVolume,jdbcType=INTEGER}");
        }
        
        if (record.getTradingAmount() != null) {
            VALUES("TRADING_AMOUNT", "#{tradingAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getAmplitudeRate() != null) {
            VALUES("AMPLITUDE_RATE", "#{amplitudeRate,jdbcType=DECIMAL}");
        }
        
        if (record.getTurnoverRate() != null) {
            VALUES("TURNOVER_RATE", "#{turnoverRate,jdbcType=DECIMAL}");
        }
        
        if (record.getGmtCreate() != null) {
            VALUES("GMT_CREATE", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            VALUES("GMT_MODIFIED", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String selectByExample(DayPriceExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ID");
        } else {
            SELECT("ID");
        }
        SELECT("CODE");
        SELECT("NAME");
        SELECT("TRADING_DATE");
        SELECT("OPENING_PRICE");
        SELECT("CLOSING_PRICE");
        SELECT("PEAK_PRICE");
        SELECT("BOTTOM_PRICE");
        SELECT("CHANGE_RATE");
        SELECT("CHANGE_AMOUNT");
        SELECT("TRADING_VOLUME");
        SELECT("TRADING_AMOUNT");
        SELECT("AMPLITUDE_RATE");
        SELECT("TURNOVER_RATE");
        SELECT("GMT_CREATE");
        SELECT("GMT_MODIFIED");
        FROM("day_price");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        DayPrice record = (DayPrice) parameter.get("record");
        DayPriceExample example = (DayPriceExample) parameter.get("example");
        
        BEGIN();
        UPDATE("day_price");
        
        if (record.getId() != null) {
            SET("ID = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getCode() != null) {
            SET("CODE = #{record.code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("NAME = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getTradingDate() != null) {
            SET("TRADING_DATE = #{record.tradingDate,jdbcType=DATE}");
        }
        
        if (record.getOpeningPrice() != null) {
            SET("OPENING_PRICE = #{record.openingPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getClosingPrice() != null) {
            SET("CLOSING_PRICE = #{record.closingPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPeakPrice() != null) {
            SET("PEAK_PRICE = #{record.peakPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getBottomPrice() != null) {
            SET("BOTTOM_PRICE = #{record.bottomPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getChangeRate() != null) {
            SET("CHANGE_RATE = #{record.changeRate,jdbcType=DECIMAL}");
        }
        
        if (record.getChangeAmount() != null) {
            SET("CHANGE_AMOUNT = #{record.changeAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getTradingVolume() != null) {
            SET("TRADING_VOLUME = #{record.tradingVolume,jdbcType=INTEGER}");
        }
        
        if (record.getTradingAmount() != null) {
            SET("TRADING_AMOUNT = #{record.tradingAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getAmplitudeRate() != null) {
            SET("AMPLITUDE_RATE = #{record.amplitudeRate,jdbcType=DECIMAL}");
        }
        
        if (record.getTurnoverRate() != null) {
            SET("TURNOVER_RATE = #{record.turnoverRate,jdbcType=DECIMAL}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("GMT_CREATE = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("GMT_MODIFIED = #{record.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("day_price");
        
        SET("ID = #{record.id,jdbcType=BIGINT}");
        SET("CODE = #{record.code,jdbcType=VARCHAR}");
        SET("NAME = #{record.name,jdbcType=VARCHAR}");
        SET("TRADING_DATE = #{record.tradingDate,jdbcType=DATE}");
        SET("OPENING_PRICE = #{record.openingPrice,jdbcType=DECIMAL}");
        SET("CLOSING_PRICE = #{record.closingPrice,jdbcType=DECIMAL}");
        SET("PEAK_PRICE = #{record.peakPrice,jdbcType=DECIMAL}");
        SET("BOTTOM_PRICE = #{record.bottomPrice,jdbcType=DECIMAL}");
        SET("CHANGE_RATE = #{record.changeRate,jdbcType=DECIMAL}");
        SET("CHANGE_AMOUNT = #{record.changeAmount,jdbcType=DECIMAL}");
        SET("TRADING_VOLUME = #{record.tradingVolume,jdbcType=INTEGER}");
        SET("TRADING_AMOUNT = #{record.tradingAmount,jdbcType=DECIMAL}");
        SET("AMPLITUDE_RATE = #{record.amplitudeRate,jdbcType=DECIMAL}");
        SET("TURNOVER_RATE = #{record.turnoverRate,jdbcType=DECIMAL}");
        SET("GMT_CREATE = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        SET("GMT_MODIFIED = #{record.gmtModified,jdbcType=TIMESTAMP}");
        
        DayPriceExample example = (DayPriceExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    public String updateByPrimaryKeySelective(DayPrice record) {
        BEGIN();
        UPDATE("day_price");
        
        if (record.getCode() != null) {
            SET("CODE = #{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("NAME = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTradingDate() != null) {
            SET("TRADING_DATE = #{tradingDate,jdbcType=DATE}");
        }
        
        if (record.getOpeningPrice() != null) {
            SET("OPENING_PRICE = #{openingPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getClosingPrice() != null) {
            SET("CLOSING_PRICE = #{closingPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPeakPrice() != null) {
            SET("PEAK_PRICE = #{peakPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getBottomPrice() != null) {
            SET("BOTTOM_PRICE = #{bottomPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getChangeRate() != null) {
            SET("CHANGE_RATE = #{changeRate,jdbcType=DECIMAL}");
        }
        
        if (record.getChangeAmount() != null) {
            SET("CHANGE_AMOUNT = #{changeAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getTradingVolume() != null) {
            SET("TRADING_VOLUME = #{tradingVolume,jdbcType=INTEGER}");
        }
        
        if (record.getTradingAmount() != null) {
            SET("TRADING_AMOUNT = #{tradingAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getAmplitudeRate() != null) {
            SET("AMPLITUDE_RATE = #{amplitudeRate,jdbcType=DECIMAL}");
        }
        
        if (record.getTurnoverRate() != null) {
            SET("TURNOVER_RATE = #{turnoverRate,jdbcType=DECIMAL}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("GMT_CREATE = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("GMT_MODIFIED = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_price
     *
     * @mbggenerated Tue Apr 16 19:42:04 CST 2024
     */
    protected void applyWhere(DayPriceExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}