package org.whatever.stockspider.db.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import org.whatever.stockspider.db.entity.FailRetryRecord;
import org.whatever.stockspider.db.entity.FailRetryRecordExample.Criteria;
import org.whatever.stockspider.db.entity.FailRetryRecordExample.Criterion;
import org.whatever.stockspider.db.entity.FailRetryRecordExample;

public class FailRetryRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String countByExample(FailRetryRecordExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("fail_retry_record");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String deleteByExample(FailRetryRecordExample example) {
        BEGIN();
        DELETE_FROM("fail_retry_record");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String insertSelective(FailRetryRecord record) {
        BEGIN();
        INSERT_INTO("fail_retry_record");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getCode() != null) {
            VALUES("CODE", "#{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("NAME", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTradingDate() != null) {
            VALUES("TRADING_DATE", "#{tradingDate,jdbcType=VARCHAR}");
        }
        
        if (record.getFailType() != null) {
            VALUES("FAIL_TYPE", "#{failType,jdbcType=VARCHAR}");
        }
        
        if (record.getRetrySucces() != null) {
            VALUES("RETRY_SUCCES", "#{retrySucces,jdbcType=INTEGER}");
        }
        
        if (record.getGmtCreate() != null) {
            VALUES("GMT_CREATE", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            VALUES("GMT_MODIFIED", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String selectByExample(FailRetryRecordExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("ID");
        } else {
            SELECT("ID");
        }
        SELECT("CODE");
        SELECT("NAME");
        SELECT("TRADING_DATE");
        SELECT("FAIL_TYPE");
        SELECT("RETRY_SUCCES");
        SELECT("GMT_CREATE");
        SELECT("GMT_MODIFIED");
        FROM("fail_retry_record");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        FailRetryRecord record = (FailRetryRecord) parameter.get("record");
        FailRetryRecordExample example = (FailRetryRecordExample) parameter.get("example");
        
        BEGIN();
        UPDATE("fail_retry_record");
        
        if (record.getId() != null) {
            SET("ID = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getCode() != null) {
            SET("CODE = #{record.code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("NAME = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getTradingDate() != null) {
            SET("TRADING_DATE = #{record.tradingDate,jdbcType=VARCHAR}");
        }
        
        if (record.getFailType() != null) {
            SET("FAIL_TYPE = #{record.failType,jdbcType=VARCHAR}");
        }
        
        if (record.getRetrySucces() != null) {
            SET("RETRY_SUCCES = #{record.retrySucces,jdbcType=INTEGER}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("GMT_CREATE = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("GMT_MODIFIED = #{record.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("fail_retry_record");
        
        SET("ID = #{record.id,jdbcType=BIGINT}");
        SET("CODE = #{record.code,jdbcType=VARCHAR}");
        SET("NAME = #{record.name,jdbcType=VARCHAR}");
        SET("TRADING_DATE = #{record.tradingDate,jdbcType=VARCHAR}");
        SET("FAIL_TYPE = #{record.failType,jdbcType=VARCHAR}");
        SET("RETRY_SUCCES = #{record.retrySucces,jdbcType=INTEGER}");
        SET("GMT_CREATE = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        SET("GMT_MODIFIED = #{record.gmtModified,jdbcType=TIMESTAMP}");
        
        FailRetryRecordExample example = (FailRetryRecordExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    public String updateByPrimaryKeySelective(FailRetryRecord record) {
        BEGIN();
        UPDATE("fail_retry_record");
        
        if (record.getCode() != null) {
            SET("CODE = #{code,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("NAME = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTradingDate() != null) {
            SET("TRADING_DATE = #{tradingDate,jdbcType=VARCHAR}");
        }
        
        if (record.getFailType() != null) {
            SET("FAIL_TYPE = #{failType,jdbcType=VARCHAR}");
        }
        
        if (record.getRetrySucces() != null) {
            SET("RETRY_SUCCES = #{retrySucces,jdbcType=INTEGER}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("GMT_CREATE = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("GMT_MODIFIED = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        WHERE("ID = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_retry_record
     *
     * @mbggenerated Mon Apr 22 10:21:38 CST 2024
     */
    protected void applyWhere(FailRetryRecordExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}