package org.whatever.stockspider.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.whatever.stockspider.db.entity.StockDividend;
import org.whatever.stockspider.db.entity.StockDividendExample;
import org.whatever.stockspider.db.entity.StockDividendKey;

public interface StockDividendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @SelectProvider(type=StockDividendSqlProvider.class, method="countByExample")
    int countByExample(StockDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @DeleteProvider(type=StockDividendSqlProvider.class, method="deleteByExample")
    int deleteByExample(StockDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @Delete({
        "delete from stock_dividend",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(StockDividendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @Insert({
        "insert into stock_dividend (ID, CODE, ",
        "NAME, IMPL_PLAN_PROFILE, ",
        "EQUITY_RECORD_DATE, EX_DIVIDEND_DATE, ",
        "NOTICE_DATE, PLAN_NOTICE_DATE, ",
        "PRETAX_BONUS_RMB, AFTERTAX_BONUS_RMB, ",
        "BASE_SHARE, HANDSEL, ",
        "TRANSFER, GMT_CREATE, ",
        "GMT_MODIFIED)",
        "values (#{id,jdbcType=BIGINT}, #{code,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{implPlanProfile,jdbcType=VARCHAR}, ",
        "#{equityRecordDate,jdbcType=TIMESTAMP}, #{exDividendDate,jdbcType=TIMESTAMP}, ",
        "#{noticeDate,jdbcType=TIMESTAMP}, #{planNoticeDate,jdbcType=TIMESTAMP}, ",
        "#{pretaxBonusRmb,jdbcType=DECIMAL}, #{aftertaxBonusRmb,jdbcType=DECIMAL}, ",
        "#{baseShare,jdbcType=INTEGER}, #{handsel,jdbcType=DECIMAL}, ",
        "#{transfer,jdbcType=DECIMAL}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtModified,jdbcType=TIMESTAMP})"
    })
    int insert(StockDividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @InsertProvider(type=StockDividendSqlProvider.class, method="insertSelective")
    int insertSelective(StockDividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @SelectProvider(type=StockDividendSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMPL_PLAN_PROFILE", property="implPlanProfile", jdbcType=JdbcType.VARCHAR),
        @Result(column="EQUITY_RECORD_DATE", property="equityRecordDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EX_DIVIDEND_DATE", property="exDividendDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="NOTICE_DATE", property="noticeDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PLAN_NOTICE_DATE", property="planNoticeDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PRETAX_BONUS_RMB", property="pretaxBonusRmb", jdbcType=JdbcType.DECIMAL),
        @Result(column="AFTERTAX_BONUS_RMB", property="aftertaxBonusRmb", jdbcType=JdbcType.DECIMAL),
        @Result(column="BASE_SHARE", property="baseShare", jdbcType=JdbcType.INTEGER),
        @Result(column="HANDSEL", property="handsel", jdbcType=JdbcType.DECIMAL),
        @Result(column="TRANSFER", property="transfer", jdbcType=JdbcType.DECIMAL),
        @Result(column="GMT_CREATE", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="GMT_MODIFIED", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<StockDividend> selectByExample(StockDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @Select({
        "select",
        "ID, CODE, NAME, IMPL_PLAN_PROFILE, EQUITY_RECORD_DATE, EX_DIVIDEND_DATE, NOTICE_DATE, ",
        "PLAN_NOTICE_DATE, PRETAX_BONUS_RMB, AFTERTAX_BONUS_RMB, BASE_SHARE, HANDSEL, ",
        "TRANSFER, GMT_CREATE, GMT_MODIFIED",
        "from stock_dividend",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="CODE", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="IMPL_PLAN_PROFILE", property="implPlanProfile", jdbcType=JdbcType.VARCHAR),
        @Result(column="EQUITY_RECORD_DATE", property="equityRecordDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EX_DIVIDEND_DATE", property="exDividendDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="NOTICE_DATE", property="noticeDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PLAN_NOTICE_DATE", property="planNoticeDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PRETAX_BONUS_RMB", property="pretaxBonusRmb", jdbcType=JdbcType.DECIMAL),
        @Result(column="AFTERTAX_BONUS_RMB", property="aftertaxBonusRmb", jdbcType=JdbcType.DECIMAL),
        @Result(column="BASE_SHARE", property="baseShare", jdbcType=JdbcType.INTEGER),
        @Result(column="HANDSEL", property="handsel", jdbcType=JdbcType.DECIMAL),
        @Result(column="TRANSFER", property="transfer", jdbcType=JdbcType.DECIMAL),
        @Result(column="GMT_CREATE", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="GMT_MODIFIED", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    StockDividend selectByPrimaryKey(StockDividendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @UpdateProvider(type=StockDividendSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") StockDividend record, @Param("example") StockDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @UpdateProvider(type=StockDividendSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") StockDividend record, @Param("example") StockDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @UpdateProvider(type=StockDividendSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(StockDividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_dividend
     *
     * @mbggenerated Tue Apr 23 11:18:21 CST 2024
     */
    @Update({
        "update stock_dividend",
        "set CODE = #{code,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "IMPL_PLAN_PROFILE = #{implPlanProfile,jdbcType=VARCHAR},",
          "EQUITY_RECORD_DATE = #{equityRecordDate,jdbcType=TIMESTAMP},",
          "EX_DIVIDEND_DATE = #{exDividendDate,jdbcType=TIMESTAMP},",
          "NOTICE_DATE = #{noticeDate,jdbcType=TIMESTAMP},",
          "PLAN_NOTICE_DATE = #{planNoticeDate,jdbcType=TIMESTAMP},",
          "PRETAX_BONUS_RMB = #{pretaxBonusRmb,jdbcType=DECIMAL},",
          "AFTERTAX_BONUS_RMB = #{aftertaxBonusRmb,jdbcType=DECIMAL},",
          "BASE_SHARE = #{baseShare,jdbcType=INTEGER},",
          "HANDSEL = #{handsel,jdbcType=DECIMAL},",
          "TRANSFER = #{transfer,jdbcType=DECIMAL},",
          "GMT_CREATE = #{gmtCreate,jdbcType=TIMESTAMP},",
          "GMT_MODIFIED = #{gmtModified,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(StockDividend record);
}